version: '3.8'
services:
        jenkins:
                image: jenkins/jenkins:lts-jdk11
                container_name: jenkins-server
                restart: on-failure
                ports:
                        - "8080:8080"
                        - "50000:50000"
                volumes:
                        - ~/jenkins_home:/var/jenkins_home
        ngrinder_controller:
                image: ngrinder/controller
                container_name: ngrinder_controller
                restart: unless-stopped
                ports:
                        - "80:80"
                        - "16001:16001"
                        - "12000-12009:12000-12009"
                volumes:
                        - ~/ngrinder-controller:/opt/ngrinder-controller
        ngrinder_agent:
                image: ngrinder/agent
                container_name: ngrinder_agent_1
                restart: unless-stopped
                depends_on:
                        - ngrinder_controller
                links:
                        - "ngrinder_controller:controller"
