version: '3.8'
services:
  frontend:
    image: node:24-alpine
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "npm ci && npm run dev"  # package-lock.json 기반 설치
    environment:
      - CHOKIDAR_USEPOLLING=true