version: '3.8'
services:
  frontend:
    image: node:24-alpine
    ports:
      - "3001:3001"
    volumes:
      - ./:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "npm ci && npm run dev"  # 일반 개발 서버 실행 (HTTPS 포함)
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development