version: '4'
services:
    mysql:
        image: mysql:8.0
        container_name: mysql_where_is
        restart: always
        ports:
            - "13306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "1234"
            TZ: Asia/Seoul
        volumes:
            - ./data:/var/lib/mysql
            - ./init:/docker-entrypoint-initdb.d
